# Generated by Django 5.1 on 2025-02-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_adminrevenuerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrevenuerecord',
            name='monthly_revenue',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
        migrations.AlterField(
            model_name='adminrevenuerecord',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
    ]
