# Generated by Django 5.0.6 on 2024-08-18 09:45

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_cartorder_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh1345', length=4, max_length=10, null=True, prefix='SKU'),
        ),
    ]
