# Generated by Django 5.0.6 on 2024-08-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_cartorder_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
