# Generated by Django 5.0.6 on 2024-08-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cartorder_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mfd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
