# Generated by Django 5.0.6 on 2024-08-25 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_product_mfd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cartorder'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.PositiveIntegerField(),
        ),
    ]
