# Generated by Django 5.0.6 on 2024-08-25 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_cartorderitem_order_alter_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
            preserve_default=False,
        ),
    ]
