# Generated by Django 5.1 on 2024-09-01 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendor', '0001_initial'),
        ('core', '0027_cartorder_payment_method_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Vendor.vendor'),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
