# Generated by Django 5.1 on 2024-09-10 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendor', '0016_payment_status'),
        ('core', '0028_alter_product_vendor_delete_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('cart_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cartorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendor.vendor')),
            ],
            options={
                'verbose_name_plural': 'Vendor Orders',
            },
        ),
    ]
