# Generated by Django 5.1 on 2024-09-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_product_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('RWF', 'Rwandan Franc')], default='USD', max_length=3),
        ),
    ]
