# Generated by Django 5.1 on 2024-10-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='shipping_method',
            new_name='shipping_fee',
        ),
    ]
