# Generated by Django 5.1 on 2024-10-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rename_shipping_method_cartorder_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
    ]
