# Generated by Django 5.1 on 2024-11-03 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendor', '0035_withdrawalrequest_currency_and_more'),
        ('core', '0041_alter_cartorder_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Vendor.vendor'),
        ),
    ]
