# Generated by Django 5.1 on 2025-02-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_product_updated'),
        ('core', '0042_alter_product_vendor'),
    ]

    operations = [
    ]
