# Generated by Django 5.1 on 2025-02-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_vendor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendor',
            new_name='VendorSaleTotal',
        ),
    ]
