# Generated by Django 5.1 on 2025-02-15 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendor', '0035_withdrawalrequest_currency_and_more'),
        ('core', '0045_rename_vendor_vendorsaletotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorsaletotal',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendor.vendor'),
        ),
    ]
