# Generated by Django 5.1 on 2025-02-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_vendorsaletotal_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorsaletotal',
            old_name='name',
            new_name='vendor',
        ),
    ]
