# Generated by Django 5.1 on 2025-02-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_rename_name_vendorsaletotal_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorSaleTotal',
        ),
    ]
