# Generated by Django 5.1 on 2025-04-15 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_product_digital_remove_product_vendor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_customer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='order_type',
            field=models.CharField(choices=[('online', 'Online'), ('in_store', 'In-Store')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
