"""
Django settings for ecomprj project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY='django-insecure-zm+&vb^2ad8z4gqfg37t(su*9d9sjxp-e!$p2w(z)!h^b6+q46'

# SECURITY WARNING: don't run with debug turned on in production!


DEBUG=True

SECURE_SSL_REDIRECT = False



ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '54ee-2c0f-eb68-69e-e500-984f-b7c-194a-7dc2.ngrok-free.app', 
]

CSRF_TRUSTED_ORIGINS = [
    'https://54ee-2c0f-eb68-69e-e500-984f-b7c-194a-7dc2.ngrok-free.app', 
]
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups' 

DEFAULT_CURRENCY = 'USD'


INSTALLED_APPS = [
    'grappelli',
    'django.contrib.humanize',
    'django.contrib.sitemaps',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'Vendor',
    'userauths',
    'taggit',
    'django_ckeditor_5',
    'crispy_forms',
    #'admin_honeypot',
    'mptt',
    'NewsLetter',
    'sslserver',
    'AdminPanel',

    #payment integration 

    'paypal.standard.ipn',
    

    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecomprj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'core.context_processor.default',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecomprj.wsgi.application'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    'site_header': "Obed Shop",
    'site_brand': "You order, we deliver",
    'site_logo': "assets/images/blog/admin.jpg",
    'copyright':"Obed.shop.com",
}

LOGIN_URL = "userauths:custom_login"

AUTH_USER_MODEL = 'userauths.Account'
# CKEditor 5 settings
CKEDITOR_5_UPLOAD_PATH = 'media/ckeditor5/'
CKEDITOR_5_UPLOAD_URL = '/media/ckeditor5/'

# ckkeditor 5 configurations 

customColorPalette = [
        {
            'color': 'hsl(4, 90%, 58%)',
            'label': 'Red'
        },
        {
            'color': 'hsl(340, 82%, 52%)',
            'label': 'Pink'
        },
        {
            'color': 'hsl(291, 64%, 42%)',
            'label': 'Purple'
        },
        {
            'color': 'hsl(262, 52%, 47%)',
            'label': 'Deep Purple'
        },
        {
            'color': 'hsl(231, 48%, 48%)',
            'label': 'Indigo'
        },
        {
            'color': 'hsl(207, 90%, 54%)',
            'label': 'Blue'
        },
    ]

# Ensure you have a proper storage class if you need custom handling
CKEDITOR_5_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Custom configuration for CKEditor 5
CKEDITOR_5_CONFIGS = {
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': [
            'heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
            'code', 'subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
            'bulletedList', 'numberedList', 'todoList', '|', 'blockQuote', 'imageUpload', '|',
            'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
            'insertTable',
        ],
        'image': {
            'toolbar': [
                        'imageStyle:inline', 'imageStyle:wrapText', 'imageStyle:breakText', '|',
                        'toggleImageCaption', 'imageTextAlternative'
                    ],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]
        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells',
                'tableProperties', 'tableCellProperties'
            ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'}
            ]
        }
    },
}


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}




EMAIL_HOST='smtp.gmail.com'
EMAIL_HOST_USER='habiyaremyeobedpatient495@gmail.com'
EMAIL_HOST_PASSWORD='rfvputeelkxehhvd'
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'

ADMIN_EMAIL = 'habiyaremyeobedpatient495@gmail.com'  # Replace with the admin email you want to receive notifications
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

PAYPAL_RECEIVER_EMAIL='sb-be33z25054294@business.example.com'
PAYPAL_TEST=True


TWILIO_ACCOUNT_SID = 'AC47cddb3d64e05149a892d0bf73a8dc14'
TWILIO_AUTH_TOKEN = '5c230c115d0f7dfba5efcc5788a894dc'
TWILIO_PHONE_NUMBER = '250789278495'

# Looking to send emails in production? Check out our Email API/SMTP product!
#EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
#EMAIL_HOST_USER = 'd5caebad0e5a40'
#EMAIL_HOST_PASSWORD = 'd5f72624029fb5'
#EMAIL_PORT = '2525'