# Generated by Django 5.1 on 2024-10-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsLetter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='recipients',
            field=models.ManyToManyField(related_name='email_templates', to='NewsLetter.subscriber'),
        ),
    ]
