# Generated by Django 5.1 on 2024-10-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsLetter', '0002_alter_emailtemplate_recipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('browser_info', models.TextField()),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('cookies', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
