# Generated by Django 5.1 on 2024-10-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsLetter', '0003_userdeviceinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeviceinfo',
            name='username',
            field=models.CharField(default='Anonymous', max_length=150),
        ),
    ]
